import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const result = await build({
  absWorkingDir: root,
  entryPoints: ['dist/global.js'],
  outfile: 'dist/bhtrees.global.js',
  bundle: true,
  format: 'iife',
  globalName: 'BHTrees',
  platform: 'browser',
  target: 'es2022',
  metafile: true,
  write: false,
  banner: { js: '// BHTrees standalone browser/game build. Generated by npm run build.\n(function () {\n"use strict";\nif ("BHTrees" in globalThis) throw new Error("BHTrees is already defined");' },
  footer: { js: 'Object.defineProperty(globalThis, "BHTrees", { value: Object.freeze(BHTrees), configurable: true, writable: true });\n})();' }
});
// Computed dynamic imports are host extension loading, not library dependencies.
for (const [path, output] of Object.entries(result.metafile.outputs)) {
  if (output.imports.length) throw new Error(`Standalone output has unresolved imports: ${path}`);
}
if (Object.keys(result.metafile.inputs).some(path => path === 'dist/node.js' || path.includes('node_modules/'))) {
  throw new Error('Standalone output contains Node adapter or package runtime code');
}
for (const file of result.outputFiles) await writeFile(file.path, file.contents);
await writeFile(new URL('../dist/bhtrees.global.d.ts', import.meta.url),
  'import type * as API from "./global.js";\ndeclare global { const BHTrees: typeof API; }\nexport {};\n');
console.log(`Standalone build: ${result.outputFiles[0].contents.length} bytes`);
